"""add_split_payment_columns

Revision ID: 417dc69b6946
Revises: a42ac81674de
Create Date: 2026-05-10 17:33:56.386473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '417dc69b6946'
down_revision: Union[str, None] = 'a42ac81674de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('cash_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('payments', sa.Column('card_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'card_amount')
    op.drop_column('payments', 'cash_amount')
    # ### end Alembic commands ###
