"""add_whatsapp_config_and_reminder_sent

Revision ID: a08f71ad09bf
Revises: 417dc69b6946
Create Date: 2026-05-10 17:46:07.465527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08f71ad09bf'
down_revision: Union[str, None] = '417dc69b6946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('whatsapp_reminder_sent', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('booking_config', sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('booking_config', sa.Column('whatsapp_reminder_hours', sa.Integer(), nullable=False, server_default='24'))
    op.add_column('booking_config', sa.Column('whatsapp_booking_message', sa.Text(), nullable=True))
    op.add_column('booking_config', sa.Column('whatsapp_reminder_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_config', 'whatsapp_reminder_message')
    op.drop_column('booking_config', 'whatsapp_booking_message')
    op.drop_column('booking_config', 'whatsapp_reminder_hours')
    op.drop_column('booking_config', 'whatsapp_enabled')
    op.drop_column('appointments', 'whatsapp_reminder_sent')
    # ### end Alembic commands ###
